version: '3.8'

networks:
  proxy-network:
    external: true

services:
  nginx:
    image: nginx:alpine
    container_name: centralized-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/log/nginx:/var/log/nginx
    networks:
      - proxy-network
    restart: unless-stopped